import { MetadataRoute } from 'next';

const baseUrl = 'https://mtverseadmin.com';

export default function sitemap(): MetadataRoute.Sitemap {
  const now = new Date();

  // Static / landing pages
  const staticPages: MetadataRoute.Sitemap = [
    {
      url: baseUrl,
      lastModified: now,
      changeFrequency: 'weekly',
      priority: 1.0,
    },
    {
      url: `${baseUrl}/pricing`,
      lastModified: now,
      changeFrequency: 'monthly',
      priority: 0.9,
    },
    {
      url: `${baseUrl}/saas-landing`,
      lastModified: now,
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: `${baseUrl}/app-landing`,
      lastModified: now,
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: `${baseUrl}/startup-landing`,
      lastModified: now,
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: `${baseUrl}/agency-landing`,
      lastModified: now,
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: `${baseUrl}/corporate-landing`,
      lastModified: now,
      changeFrequency: 'monthly',
      priority: 0.7,
    },
    {
      url: `${baseUrl}/product-landing`,
      lastModified: now,
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: `${baseUrl}/portfolio-landing`,
      lastModified: now,
      changeFrequency: 'monthly',
      priority: 0.7,
    },
    {
      url: `${baseUrl}/ebook-landing`,
      lastModified: now,
      changeFrequency: 'monthly',
      priority: 0.7,
    },
    {
      url: `${baseUrl}/course-landing`,
      lastModified: now,
      changeFrequency: 'monthly',
      priority: 0.7,
    },
    {
      url: `${baseUrl}/event-landing`,
      lastModified: now,
      changeFrequency: 'monthly',
      priority: 0.7,
    },
  ];

  // Auth pages
  const authPages: MetadataRoute.Sitemap = [
    'sign-in',
    'sign-up',
    'forgot-password',
    'reset-password',
    'confirm-password',
    'two-step',
    'multi-factor',
    'lock-screen',
    'email-verification',
    'welcome-screen',
    'social-login',
    'password-changed',
  ].map((page) => ({
    url: `${baseUrl}/${page}`,
    lastModified: now,
    changeFrequency: 'monthly' as const,
    priority: 0.5,
  }));

  // Dashboard pages
  const dashboards = [
    'ecommerce',
    'analytics',
    'marketing',
    'crm',
    'stocks',
    'saas',
    'logistics',
    'ai',
    'sales',
    'finance',
    'crypto',
    'hospital',
    'school',
    'restaurant',
    'real-estate',
  ];

  const dashboardPages: MetadataRoute.Sitemap = dashboards.map((d) => ({
    url: `${baseUrl}/dashboards/${d}`,
    lastModified: now,
    changeFrequency: 'weekly',
    priority: 0.8,
  }));

  // Component pages
  const componentPages: MetadataRoute.Sitemap = [
    'ui-elements',
    'advanced-ui',
    'extended-ui',
    'forms',
    'tables',
    'charts',
  ].map((c) => ({
    url: `${baseUrl}/components/${c}`,
    lastModified: now,
    changeFrequency: 'weekly',
    priority: 0.8,
  }));

  // UI Elements sub-pages
  const uiElementPages: MetadataRoute.Sitemap = [
    'buttons',
    'badges',
    'cards',
    'alerts',
    'accordions',
    'avatars',
    'avatar-groups',
    'breadcrumbs',
    'carousels',
    'code-block',
    'code-highlighters',
    'color-swatches',
    'command-palette',
    'copy-button',
    'count-ups',
    'descriptions',
    'dividers',
    'dot-indicators',
    'drawers',
    'dropdowns',
    'empty-states',
    'glass-morphism',
    'glow-effects',
    'gradients',
    'headings',
    'highlight-text',
    'icon-buttons',
    'indicators',
    'kbd-shortcuts',
    'lists',
    'media-objects',
    'metric-cards',
    'modals',
    'notification-panel',
    'pagination',
    'popovers',
    'progress',
    'ribbons',
    'scrollable',
    'separators',
    'shadows',
    'skeletons',
    'spinners',
    'stat-cards',
    'status-badges',
    'tabs',
    'tag-input',
    'timeline',
    'toasts',
    'tooltips',
    'typography',
    'animated-text',
    'aspect-ratios',
    'blockquote',
    'button-groups',
    'carousels',
  ].map((c) => ({
    url: `${baseUrl}/ui-elements/${c}`,
    lastModified: now,
    changeFrequency: 'monthly',
    priority: 0.7,
  }));

  // Advanced UI sub-pages
  const advancedUIPages: MetadataRoute.Sitemap = [
    'accordion-animated',
    'gradient-orb',
    'confetti-button',
    'card-swap',
    'blob-animation',
    '3d-card',
    'xylophone-bars',
    'stagger-cards',
    'glow-ring',
    'slide-in-panel',
    'glass-morphism-panel',
    'canvas-particles',
    'keyframe-rotate',
    'floating-labels',
    'glow-text',
    'marquee-text',
    'vortex-loader',
    'matrix-rain',
    'jump-text',
    'slide-elastic',
    'oscillate-loader',
    'pull-to-refresh',
    'orbit-dots',
    'gradient-text',
    'blur-transition',
    'jelly-button',
    'orbit-spinner',
    'accordion-slide',
    'morph-input',
    'progress-circle-animated',
    'piston-loader',
    'morph-tabs',
    'wave-canvas',
    'hover-morph',
    'hover-depth',
    'vortex-card',
    'kaleidoscope',
    'gradient-border',
    'ripple-button',
    'hover-glow',
    'scale-hover',
    'chart-live',
    'fade-in-image',
    'firework-button',
    'kinetic-typography',
    'ghost-card',
    'wave-text',
    'radial-menu',
    'fade-grid',
    'zoom-gallery',
    'spin-loader',
    'background-shift',
    'toggle-switch-animated',
    'elastic-grid',
    'elastic-list',
    'accordion-tree',
    'bounce-scroll',
    'depth-card',
    'bubble-animation',
    'elastic-input',
    'elastic-scroll',
    'lava-menu',
    'morphing-icon',
    'interactive-mesh',
    'parallax-text',
    'morphing-shape',
    'orbit-system',
    'scale-reveal',
    'sidebar-animated',
    'magnetic-button',
    'vibrate-button',
    'tooltip-animated',
    'neon-border',
    'gravity-list',
    'accordion-group',
    'marquee-infinite',
    'vortex-spinner',
    '3d-flip-card',
    'floating-dock',
    'stretch-text',
    'floating-cards',
    'radio-animated',
    'toggle-morph',
    'swipe-deck',
    'cable-animation',
    'swipeable-list-item',
    'orbit-menu',
    'flare-button',
    'spring-list',
    'wobble-button',
    'shake-input',
    'cursor-glow',
    'slide-reveal',
    'spotlight-card',
    'path-animation',
    'reveal-card',
    'card-tilt',
    'accordion-expand',
    'distort-effect',
    'float-animation',
    'radial-progress',
    'yield-animation',
    'zoom-morph',
    'glass-card',
    'card-flip-3d',
    'skew-card',
    'glow-button',
    'tilt-gallery',
    'orbit-loader',
    'neon-pulse',
    'hologram-card',
    'blend-card',
    'twist-card',
    'snap-scroll',
    'jello-effect',
    'jelly-card',
    'counter-wheel',
    'stagger-list',
    'morph-dialog',
    'animated-counter',
    'bento-grid',
    'floating-action',
    'morph-button-group',
    'wave-button',
    'ember-glow',
    'spotlight-focus',
    'confetti-explosion',
    'tilt-card',
    'elastic-button',
    'zen-background',
    'drag-sort',
    'stagger-animation',
    'physics-card',
    'pulse-dot',
    'rain-effect',
    'magnetic-cards',
    'neon-glow',
    'morphing-layout',
    'neon-text',
    'bouncing-dots',
    'breathing-card',
    'gradient-flow',
    'hexagon-grid',
    'progress-step-animated',
    'wave-text-animation',
    'expandable-search',
    'draggable-card',
    'zigzag-divider',
    'floating-action-button',
    'blur-reveal',
    'parallax-scroll',
    'flip-board',
    'shimmer-loader',
    'underwave',
    'particle-button',
    'galaxy-background',
    'neon-switch',
    'accordion-reveal',
    'knob-control',
    'drawer-animated',
    'particle-network',
    'quicksand-effect',
    'bounce-notification',
    'knob-spinner',
    'stepper-navigation',
    'accordion-drag',
    'typewriter-loop',
    'isometric-grid',
    'elastic-slider',
    'typing-effect',
    'progress-morph',
    'dropdown-menu-animated',
    'hover-board',
    'lava-lamp',
    'error-boundary-fallback',
    'interactive-grid',
    'unfold-card',
    'wave-background',
    'slide-up-modal',
    'physics-simulation',
    'data-typewriter',
    'drift-animation',
    'inverse-card',
    'skeleton-wave',
    'glitch-text',
    'neon-button',
    'ion-background',
    'neon-line',
    'checkbox-animated',
    'shake-effect',
    'drag-preview',
    'rotating-text',
    'hover-scale',
    'jump-button',
    'shimmer-border',
    'animated-border',
    'dna-helix',
    'flip-card',
    'spotlight-search',
    'rotating-loader',
    'liquid-button',
    'infinite-scroll-loader',
    'elastic-toggle',
    'lava-button',
    'liquid-nav',
    'success-animation',
    'spring-button',
    'typewriter-text',
    'card-stack',
    'aurora-background',
    'glow-panel',
    'aurora-card',
    'blur-card',
    'popover-animated',
    'jelly-grid',
    'tab-indicator',
    'gradient-mesh',
    'x-ray-card',
    'blur-reveal-content',
    'toast-stack',
    'pie-spin',
    'ripple-effect',
    'particle-background',
    'parallax-card',
    'lens-effect',
    'reveal-animation',
    'water-ripple',
    'masonry-grid',
    'safari-card',
    'parallax-gallery',
  ].map((c) => ({
    url: `${baseUrl}/advanced-ui/${c}`,
    lastModified: now,
    changeFrequency: 'monthly',
    priority: 0.7,
  }));

  // Extended UI sub-pages
  const extendedUIPages: MetadataRoute.Sitemap = [
    'document-viewer',
    'weather-widget',
    'benefit-card',
    'habit-tracker',
    'notification-hub',
    'media-browser',
    'pricing-toggle',
    'file-list',
    'search-results',
    'bug-tracker',
    'cookie-consent',
    'grade-book',
    'task-organizer',
    'poll-widget',
    'scheduling-board',
    'qr-code',
    'outcome-tracker',
    'payment-form',
    'diagram-viewer',
    'yaml-editor',
    'analytics-funnel',
    'billing-card',
    'video-player',
    'knowledge-base',
    'event-scheduler',
    'user-permissions',
    'date-display',
    'log-viewer',
    'test-runner',
    'note-organizer',
    'health-dashboard',
    'quiz-component',
    'share-button',
    'event-log',
    'file-browser',
    'version-history',
    'estimate-calculator',
    'hex-picker',
    'quote-generator',
    'deployment-log',
    'user-directory',
    'tour-guide',
    'activity-feed',
    'info-banner',
    'workflow-designer',
    'breadcrumb-trail',
    'pipeline-view',
    'chart-builder',
    'layout-builder',
    'comparison-slider',
    'milestone-tracker',
    'like-button',
    'analytics-widget',
    'audio-player',
    'map-placeholder',
    'badge-system',
    'vendor-list',
    'avatar-upload',
    'contact-card',
    'color-palette',
    'bookmark-button',
    'fleet-monitor',
    'heatmap-calendar',
    'stock-ticker',
    'feedback-form',
    'calendar-scheduler',
    'learning-path',
    'sprint-retrospective',
    'tag-manager',
    'syntax-highlight',
    'xml-viewer',
    'rich-text-editor',
    'fullscreen-toggle',
    'webhook-editor',
    'inventory-grid',
    'chat-bubble',
    'workspace-switcher',
    'shopping-list',
    'competency-matrix',
    'team-pulse',
    'code-editor',
    'weather-dashboard',
    'badge-collection',
    'escalation-matrix',
    'checklist-advanced',
    'skill-radar',
    'task-dependency',
    'profile-card',
    'calendar-widget',
    'permission-grid',
    'job-application',
    'network-graph',
    'reaction-picker',
    'warning-banner',
    'membership-card',
    'code-review',
    'email-template',
    'feedback-collector',
    'json-tree',
    'wiki-editor',
    'spreadsheet-mini',
    'kanban-advanced',
    'risk-register',
    'announcement-bar',
    'carousel',
    'version-diff',
    'keyboard-nav',
    'image-compare',
    'org-tree',
    'zip-explorer',
    'coupon-generator',
    'sprint-board',
    'pipeline-editor',
    'donut-chart',
    'branch-selector',
    'file-tree',
    'retro-board',
    'onboarding-tooltip',
    'question-bank',
    'quiz-builder',
    'live-region',
    'chart-widget',
    'capacity-planner',
    'chart-placeholder',
    'unit-converter',
    'job-queue',
    'keyboard-shortcuts',
    'journal-calendar',
    'screen-reader-only',
    'newsletter-builder',
    'iteration-board',
    'color-picker',
    'activity-heatmap',
    'decision-matrix',
    'gantt-chart',
    'form-wizard',
    'resource-allocator',
    'excel-grid',
    'whiteboard-mini',
    'query-builder',
    'kanban-swimlane',
    'xray-viewer',
    'command-palette',
    'hashtag-input',
    'key-result-tracker',
    'filter-panel',
    'otp-verification',
    'backlog-prioritizer',
    'daily-planner',
    'calendar-heatmap',
    'notification-panel',
    'merge-request',
    'book-reader',
    'inspection-form',
    'recipe-card',
    'print-button',
    'org-chart',
    'velocity-chart',
    'uptime-monitor',
    'idea-board',
    'progress-dashboard',
    'time-display',
    'stat-widget',
    'chat-interface',
    'performance-review',
    'hr-dashboard',
    'bookmark-manager',
    'mention-input',
    'video-conference',
    'feature-flag',
    'git-diff-viewer',
    'onboarding-steps',
    'approval-flow',
    'skip-link',
    'lightbox',
    'gallery-grid',
    'invoice-builder',
    'command-input',
    'data-table-mini',
    'comment-thread',
    'barcode-scanner',
    'budget-tracker',
    'image-editor',
    'changelog-viewer',
    'release-notes',
    'access-log',
    'tag-cloud',
    'survey-form',
    'account-selector',
    'diff-viewer',
    'usage-analytics',
    'dropzone-area',
    'order-tracker',
    'wizard-nav',
    'role-manager',
    'license-manager',
    'diff-editor',
    'journal-entry',
    'incident-tracker',
    'navigation-breadcrumb',
    'copy-to-clipboard',
    'data-explorer',
    'markdown-preview',
    'product-card',
    'social-card',
    'key-manager',
    'workout-planner',
    'forum-thread',
    'link-shortener',
    'focus-trap',
    'value-stream',
    'metric-gauge',
    'flag-manager',
    'maintenance-banner',
    'metric-board',
    'address-book',
    'stepper-form',
    'integration-panel',
    'audio-visualizer',
    'kanban-board',
    'geo-autocomplete',
    'rating-stars',
    'activity-timeline',
    'cookie-banner',
    'goal-tracker',
    'timeline-advanced',
    'avatar-group',
    'follow-button',
    'markdown-editor-ext',
    'map-locator',
    'dependency-graph',
  ].map((c) => ({
    url: `${baseUrl}/extended-ui/${c}`,
    lastModified: now,
    changeFrequency: 'monthly',
    priority: 0.7,
  }));

  // Source code pages
  const sourceCodeCategories = ['ui-elements', 'advanced-ui', 'extended-ui'];
  const sourceCodePages: MetadataRoute.Sitemap = [];

  const sourceCodeComponents: Record<string, string[]> = {
    'ui-elements': [
      'scroll-indicator',
      'toolbar-actions',
      'dividers',
      'group-checkbox',
      'breadcrumb-separator',
      'virtual-list-ui',
      'toasts',
      'sticky-note',
      'segmented-control',
      'media-card',
      'thumb-rating',
      'inline-edit',
      'step-nav',
      'gradient-text',
      'pie-mini',
      'card-interactive',
      'counter-inline',
      'expandable-text',
      'toast-notification',
      'icon-badge',
      'spinner-bar',
      'toggle-button-group',
      'year-picker',
      'empty-states',
      'button-loading',
      'dropdown-group',
      'color-swatch-row',
      'skeletons',
      'counter-badge',
      'meta-tag',
      'zoom-control',
      'sticky-header-ui',
      'form-field',
      'skeleton-table',
      'code-block',
      'gradient-header',
      'tabs',
      'labeled-input',
      'verification-input',
      'image-gallery-mini',
      'wrap-tag',
      'color-swatches',
      'checkboxes',
      'wizard-progress',
      'accordions',
      'badge-stack',
      'breadcrumb-icon',
      'tag-input',
      'key-value-grid',
      'status-pulse',
      'pill-badge',
      'react-badge',
      'upload-progress',
      'spinners',
      'rating-display',
      'drag-handle-list',
      'password-toggle',
      'quantity-input',
      'progress',
      'size-selector',
      'card-collapsible',
      'expand-button',
      'link-button',
      'pagination',
      'drag-indicator',
      'theme-switcher',
      'word-counter',
      'key-value-list',
      'summary-card',
      'quick-action-bar',
      'expand-collapse',
      'number-input-spinner',
      'avatars',
      'file-upload',
      'nav-pill',
      'status-indicator',
      'user-avatar-group',
      'breadcrumb',
      'countdown-timer',
      'comparison-toggle',
      'resizable-panel',
      'signal-indicator',
      'action-menu',
      'alert-dismissible',
      'truncated-text',
      'number-counter',
      'notification-badge',
      'avatar-stack-horizontal',
      'tooltip-rich',
      'mini-chart',
      'week-picker',
      'chip-select',
      'progress-ring',
      'filter-dropdown',
      'dropdown-overflow',
      'option-toggle',
      'radio-groups',
      'radio-card',
      'date-input',
      'loading-dots',
      'icon-toggle',
      'sidebar-mini',
      'tooltip-click',
      'form-group',
      'overflow-menu',
      'image-placeholder',
      'wizard-step-ui',
      'text-highlight',
      'date-range-badge',
      'accordion-multi',
      'time-badge',
      'option-card',
      'group-radio',
      'alerts',
      'link-preview',
      'text-truncate',
      'animated-underline',
      'image-crop-preview',
      'gradient-border-card',
      'chip-removable',
      'media-object',
      'badge-overlay',
      'menu-item',
      'buttons',
      'list-checkable',
      'counter-animated',
      'textareas',
      'button-icon-split',
      'inline-notification',
      'filter-chip',
      'breadcrumb-dropdown',
      'user-menu',
      'floating-label',
      'nested-list',
      'tab-closable',
      'select-grouped',
      'alert-banner',
      'swap-button',
      'icon-picker',
      'sort-indicator',
      'keyboard-keys',
      'badges',
      'overlay-trigger',
      'video-placeholder',
      'grouped-avatar',
      'cards',
      'icon-showcase',
      'gradient-text-box',
      'mini-stat-card',
      'toast-stack-ui',
      'range-sliders',
      'preview-card',
      'widget-stat',
      'chips',
      'date-badge',
      'select-combo',
      'collapsible-sections',
      'multi-select-chip',
      'timelines',
      'text-inputs',
      'select-menus',
      'breadcrumb-trail-ui',
      'upload-zone',
      'progress-step',
      'wave-divider',
      'filter-bar',
      'chip-input',
      'scroll-shadow',
      'color-dot',
      'verification-badge',
      'avatar-dropdown',
      'loading-skeleton',
      'dropdown-checklist',
      'tree-item',
      'slider-range',
      'dot-loader',
      'placeholder-shimmer',
      'multi-progress',
      'search-filter',
      'tag-closable',
      'switches',
      'typography',
      'modals',
      'accordion-sidebar',
      'popovers',
      'tooltips',
      'metric-cards',
      'menu-dropdown',
      'password-strength',
      'avatar-status',
      'tab-scrollable',
      'drawer-panel',
      'list-draggable',
      'tabs-with-icons',
      'label-tag',
      'button-dropdown',
      'spinner-dot',
      'snippet-code',
      'card-stats',
      'vertical-nav',
      'toggle-chip',
      'sub-menu',
      'color-picker-mini',
      'dropdowns',
      'sortable-list',
      'badge-group',
      'view-toggle',
      'data-tags',
      'stacked-card',
    ],
    'advanced-ui': [
      'accordion-animated',
      'gradient-orb',
      'confetti-button',
      'card-swap',
      'blob-animation',
      '3d-card',
      'xylophone-bars',
      'stagger-cards',
      'glow-ring',
      'slide-in-panel',
      'glass-morphism-panel',
      'canvas-particles',
      'keyframe-rotate',
      'floating-labels',
      'glow-text',
      'marquee-text',
      'vortex-loader',
      'matrix-rain',
      'jump-text',
      'slide-elastic',
      'oscillate-loader',
      'pull-to-refresh',
      'orbit-dots',
      'gradient-text',
      'blur-transition',
      'jelly-button',
      'orbit-spinner',
      'accordion-slide',
      'morph-input',
      'progress-circle-animated',
      'piston-loader',
      'morph-tabs',
      'wave-canvas',
      'hover-morph',
      'hover-depth',
      'vortex-card',
      'kaleidoscope',
      'gradient-border',
      'ripple-button',
      'hover-glow',
      'scale-hover',
      'chart-live',
      'fade-in-image',
      'firework-button',
      'kinetic-typography',
      'ghost-card',
      'wave-text',
      'radial-menu',
      'fade-grid',
      'zoom-gallery',
      'spin-loader',
      'background-shift',
      'toggle-switch-animated',
      'elastic-grid',
      'elastic-list',
      'accordion-tree',
      'bounce-scroll',
      'depth-card',
      'bubble-animation',
      'elastic-input',
      'elastic-scroll',
      'lava-menu',
      'morphing-icon',
      'interactive-mesh',
      'parallax-text',
      'morphing-shape',
      'orbit-system',
      'scale-reveal',
      'sidebar-animated',
      'magnetic-button',
      'vibrate-button',
      'tooltip-animated',
      'neon-border',
      'gravity-list',
      'accordion-group',
      'marquee-infinite',
      'vortex-spinner',
      '3d-flip-card',
      'floating-dock',
      'stretch-text',
      'floating-cards',
      'radio-animated',
      'toggle-morph',
      'swipe-deck',
      'cable-animation',
      'swipeable-list-item',
      'orbit-menu',
      'flare-button',
      'spring-list',
      'wobble-button',
      'shake-input',
      'cursor-glow',
      'slide-reveal',
      'spotlight-card',
      'path-animation',
      'reveal-card',
      'card-tilt',
      'accordion-expand',
      'distort-effect',
      'float-animation',
      'radial-progress',
      'yield-animation',
      'zoom-morph',
      'glass-card',
      'card-flip-3d',
      'skew-card',
      'glow-button',
      'tilt-gallery',
      'orbit-loader',
      'neon-pulse',
      'hologram-card',
      'blend-card',
      'twist-card',
      'snap-scroll',
      'jello-effect',
      'jelly-card',
      'counter-wheel',
      'stagger-list',
      'morph-dialog',
      'animated-counter',
      'bento-grid',
      'floating-action',
      'morph-button-group',
      'wave-button',
      'ember-glow',
      'spotlight-focus',
      'confetti-explosion',
      'tilt-card',
      'elastic-button',
      'zen-background',
      'drag-sort',
      'stagger-animation',
      'physics-card',
      'pulse-dot',
      'rain-effect',
      'magnetic-cards',
      'neon-glow',
      'morphing-layout',
      'neon-text',
      'bouncing-dots',
      'breathing-card',
      'gradient-flow',
      'hexagon-grid',
      'progress-step-animated',
      'wave-text-animation',
      'expandable-search',
      'draggable-card',
      'zigzag-divider',
      'floating-action-button',
      'blur-reveal',
      'parallax-scroll',
      'flip-board',
      'shimmer-loader',
      'underwave',
      'particle-button',
      'galaxy-background',
      'neon-switch',
      'accordion-reveal',
      'knob-control',
      'drawer-animated',
      'particle-network',
      'quicksand-effect',
      'bounce-notification',
      'knob-spinner',
      'stepper-navigation',
      'accordion-drag',
      'typewriter-loop',
      'isometric-grid',
      'elastic-slider',
      'typing-effect',
      'progress-morph',
      'dropdown-menu-animated',
      'hover-board',
      'lava-lamp',
      'error-boundary-fallback',
      'interactive-grid',
      'unfold-card',
      'wave-background',
      'slide-up-modal',
      'physics-simulation',
      'data-typewriter',
      'drift-animation',
      'inverse-card',
      'skeleton-wave',
      'glitch-text',
      'neon-button',
      'ion-background',
      'neon-line',
      'checkbox-animated',
      'shake-effect',
      'drag-preview',
      'rotating-text',
      'hover-scale',
      'jump-button',
      'shimmer-border',
      'animated-border',
      'dna-helix',
      'flip-card',
      'spotlight-search',
      'rotating-loader',
      'liquid-button',
      'infinite-scroll-loader',
      'elastic-toggle',
      'lava-button',
      'liquid-nav',
      'success-animation',
      'spring-button',
      'typewriter-text',
      'card-stack',
      'aurora-background',
      'glow-panel',
      'aurora-card',
      'blur-card',
      'popover-animated',
      'jelly-grid',
      'tab-indicator',
      'gradient-mesh',
      'x-ray-card',
      'blur-reveal-content',
      'toast-stack',
      'pie-spin',
      'ripple-effect',
      'particle-background',
      'parallax-card',
      'lens-effect',
      'reveal-animation',
      'water-ripple',
      'masonry-grid',
      'safari-card',
      'parallax-gallery',
    ],
    'extended-ui': [
      'document-viewer',
      'weather-widget',
      'benefit-card',
      'habit-tracker',
      'notification-hub',
      'media-browser',
      'pricing-toggle',
      'file-list',
      'search-results',
      'bug-tracker',
      'cookie-consent',
      'grade-book',
      'task-organizer',
      'poll-widget',
      'scheduling-board',
      'qr-code',
      'outcome-tracker',
      'payment-form',
      'diagram-viewer',
      'yaml-editor',
      'analytics-funnel',
      'billing-card',
      'video-player',
      'knowledge-base',
      'event-scheduler',
      'user-permissions',
      'date-display',
      'log-viewer',
      'test-runner',
      'note-organizer',
      'health-dashboard',
      'quiz-component',
      'share-button',
      'event-log',
      'file-browser',
      'version-history',
      'estimate-calculator',
      'hex-picker',
      'quote-generator',
      'deployment-log',
      'user-directory',
      'tour-guide',
      'activity-feed',
      'info-banner',
      'workflow-designer',
      'breadcrumb-trail',
      'pipeline-view',
      'chart-builder',
      'layout-builder',
      'comparison-slider',
      'milestone-tracker',
      'like-button',
      'analytics-widget',
      'audio-player',
      'map-placeholder',
      'badge-system',
      'vendor-list',
      'avatar-upload',
      'contact-card',
      'color-palette',
      'bookmark-button',
      'fleet-monitor',
      'heatmap-calendar',
      'stock-ticker',
      'feedback-form',
      'calendar-scheduler',
      'learning-path',
      'sprint-retrospective',
      'tag-manager',
      'syntax-highlight',
      'xml-viewer',
      'rich-text-editor',
      'fullscreen-toggle',
      'webhook-editor',
      'inventory-grid',
      'chat-bubble',
      'workspace-switcher',
      'shopping-list',
      'competency-matrix',
      'team-pulse',
      'code-editor',
      'weather-dashboard',
      'badge-collection',
      'escalation-matrix',
      'checklist-advanced',
      'skill-radar',
      'task-dependency',
      'profile-card',
      'calendar-widget',
      'permission-grid',
      'job-application',
      'network-graph',
      'reaction-picker',
      'warning-banner',
      'membership-card',
      'code-review',
      'email-template',
      'feedback-collector',
      'json-tree',
      'wiki-editor',
      'spreadsheet-mini',
      'kanban-advanced',
      'risk-register',
      'announcement-bar',
      'carousel',
      'version-diff',
      'keyboard-nav',
      'image-compare',
      'org-tree',
      'zip-explorer',
      'coupon-generator',
      'sprint-board',
      'pipeline-editor',
      'donut-chart',
      'branch-selector',
      'file-tree',
      'retro-board',
      'onboarding-tooltip',
      'question-bank',
      'quiz-builder',
      'live-region',
      'chart-widget',
      'capacity-planner',
      'chart-placeholder',
      'unit-converter',
      'job-queue',
      'keyboard-shortcuts',
      'journal-calendar',
      'screen-reader-only',
      'newsletter-builder',
      'iteration-board',
      'color-picker',
      'activity-heatmap',
      'decision-matrix',
      'gantt-chart',
      'form-wizard',
      'resource-allocator',
      'excel-grid',
      'whiteboard-mini',
      'query-builder',
      'kanban-swimlane',
      'xray-viewer',
      'command-palette',
      'hashtag-input',
      'key-result-tracker',
      'filter-panel',
      'otp-verification',
      'backlog-prioritizer',
      'daily-planner',
      'calendar-heatmap',
      'notification-panel',
      'merge-request',
      'book-reader',
      'inspection-form',
      'recipe-card',
      'print-button',
      'org-chart',
      'velocity-chart',
      'uptime-monitor',
      'idea-board',
      'progress-dashboard',
      'time-display',
      'stat-widget',
      'chat-interface',
      'performance-review',
      'hr-dashboard',
      'bookmark-manager',
      'mention-input',
      'video-conference',
      'feature-flag',
      'git-diff-viewer',
      'onboarding-steps',
      'approval-flow',
      'skip-link',
      'lightbox',
      'gallery-grid',
      'invoice-builder',
      'command-input',
      'data-table-mini',
      'comment-thread',
      'barcode-scanner',
      'budget-tracker',
      'image-editor',
      'changelog-viewer',
      'release-notes',
      'access-log',
      'tag-cloud',
      'survey-form',
      'account-selector',
      'diff-viewer',
      'usage-analytics',
      'dropzone-area',
      'order-tracker',
      'wizard-nav',
      'role-manager',
      'license-manager',
      'diff-editor',
      'journal-entry',
      'incident-tracker',
      'navigation-breadcrumb',
      'copy-to-clipboard',
      'data-explorer',
      'markdown-preview',
      'product-card',
      'social-card',
      'key-manager',
      'workout-planner',
      'forum-thread',
      'link-shortener',
      'focus-trap',
      'value-stream',
      'metric-gauge',
      'flag-manager',
      'maintenance-banner',
      'metric-board',
      'address-book',
      'stepper-form',
      'integration-panel',
      'audio-visualizer',
      'kanban-board',
      'geo-autocomplete',
      'rating-stars',
      'activity-timeline',
      'cookie-banner',
      'goal-tracker',
      'timeline-advanced',
      'avatar-group',
      'follow-button',
      'markdown-editor-ext',
      'map-locator',
      'dependency-graph',
    ],
  };

  for (const category of sourceCodeCategories) {
    const components = sourceCodeComponents[category] || [];
    for (const component of components) {
      sourceCodePages.push({
        url: `${baseUrl}/source/${category}/${component}`,
        lastModified: now,
        changeFrequency: 'monthly',
        priority: 0.6,
      });
    }
  }

  // App pages
  const appPages: MetadataRoute.Sitemap = [
    'calendar',
    'chat',
    'email',
    'tasks',
    'file-manager',
    'support',
    'kanban',
    'projects',
    'contacts',
    'notes',
    'calculator',
    'weather',
    'video-player',
    'music-player',
    'photo-gallery',
    'bookmarks',
  ].map((a) => ({
    url: `${baseUrl}/apps/${a}`,
    lastModified: now,
    changeFrequency: 'monthly',
    priority: 0.7,
  }));

  // E-commerce pages
  const ecommercePages: MetadataRoute.Sitemap = [
    'products',
    'orders',
    'invoices',
    'transactions',
    'coupons',
    'wishlist',
    'shop-cart',
    'add-product',
    'product-detail',
    'product-comparison',
    'order-detail',
    'reviews',
    'vendors',
    'inventory',
    'returns',
    'analytics-ecom',
    'create-invoice',
  ].map((e) => ({
    url: `${baseUrl}/ecommerce/${e}`,
    lastModified: now,
    changeFrequency: 'monthly',
    priority: 0.7,
  }));

  // AI pages
  const aiPages: MetadataRoute.Sitemap = [
    'ai-chat',
    'text-generator',
    'image-generator',
    'code-generator',
    'ai-summarizer',
    'ai-data-analysis',
    'ai-assistant',
    'ai-code-review',
    'ai-translator',
    'ai-workflow',
    'ai-models',
    'prompt-history',
  ].map((a) => ({
    url: `${baseUrl}/ai/${a}`,
    lastModified: now,
    changeFrequency: 'monthly',
    priority: 0.7,
  }));

  // Chart pages
  const chartPages: MetadataRoute.Sitemap = [
    'line-chart',
    'bar-chart',
    'area-chart',
    'pie-chart',
    'donut-chart',
    'radar-chart',
    'scatter-chart',
    'bubble-chart',
    'candlestick-chart',
    'heatmap-chart',
    'treemap-chart',
    'funnel-chart',
    'gauge-chart',
    'sparkline-chart',
    'stacked-bar-chart',
    'stacked-area-chart',
    'mixed-chart',
    'waterfall-chart',
    'bullet-chart',
    'radial-chart',
    'step-chart',
    'campaign-chart',
    'conversion-chart',
    'revenue-chart',
    'traffic-chart',
    'expense-chart',
    'sales-chart',
    'portfolio-chart',
    'cashflow-chart',
    'user-growth-chart',
    'grouped-bar-chart',
    'geographic-chart',
    'device-chart',
    'sunburst-chart',
    'token-usage-chart',
  ].map((c) => ({
    url: `${baseUrl}/charts/${c}`,
    lastModified: now,
    changeFrequency: 'monthly',
    priority: 0.6,
  }));

  // Table pages
  const tablePages: MetadataRoute.Sitemap = [
    'basic-table',
    'data-table',
    'editable-table',
    'expandable-table',
    'filterable-table',
    'grouped-table',
    'hierarchy-table',
    'orders-table',
    'pivot-table',
    'pricing-table',
    'responsive-table',
    'schedule-table',
    'selectable-table',
    'status-table',
    'timeline-table',
    'transaction-table',
    'analytics-table',
    'comparison-table',
  ].map((t) => ({
    url: `${baseUrl}/tables/${t}`,
    lastModified: now,
    changeFrequency: 'monthly',
    priority: 0.6,
  }));

  return [
    ...staticPages,
    ...authPages,
    ...dashboardPages,
    ...componentPages,
    ...uiElementPages,
    ...advancedUIPages,
    ...extendedUIPages,
    ...sourceCodePages,
    ...appPages,
    ...ecommercePages,
    ...aiPages,
    ...chartPages,
    ...tablePages,
  ];
}
